import type { Metadata } from "next";
import "./globals.css";
import classNames from "classnames";
import { AppFont } from "./Font";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={classNames(`${AppFont.Inter.variable} ${AppFont.Koulen.variable}  `)} >
      <body className="bg-black">{children}</body>
    </html >
  );
}
